### ISSUE TITLE
Links issue 

### ISSUE THREAD

**Issue by faytor** [bklevence/MagTag_Moon#1]
Hi, 
The link (MagTag) points to something else :)...Is this done on purpose?
And the Curtis Clark's Moon Typface link is dead !

**Comment by bklevence** [comment]
Lol, ty! Too many projects I was documenting at the same time I guess. Curtis Clark typeface, I updated w/ a new link, and it looks like the old link isn't on wayback machine unfortunately. Doing some quick searching there are many other sources.
